### ISSUE TITLE
Theme fonts not being used

### ISSUE THREAD

**Issue by dubefab** [7368697661/Origami#10]
Just installed this theme, lovely. The headers use the Fraunces font, but that's about it.
IBM Plex not being used in interface neither Fraunces in normal test.
I had to manually set it in the Obsidian preferences.

**Comment by joelatschool** [comment]
Just to confirm, having the same issue

**Comment by 7368697661** [comment]
should be an initial fix pushed now! i had to remove ibm for now, sadly, but am planning a big typography update with 2.0 to bring it and some others back :)
