### ISSUE TITLE
Toggle jumps vertically when cursor passes it.

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#12]
I don't think this is the intended behaviour, when the mouse cursor passes toggle buttons, the button seems to be jumping vertically out of it's "slide path". It also behaves erraticaly around that pointing (jumping back and down again). Screenshot of the displaced mode:

![Screenshot_2023-02-05_21-04-33](https://user-images.githubusercontent.com/38863/216823576-4d54f5b4-6dcb-4d76-a26b-ec00fdefe0a1.png)

Happens both in the Linux and MacOS environment, just checked in case the system makes a difference.

- Obsidian version: 1.1.9
- Origami version: 1.0.0.2

Happy to help if there's something I can.

**Comment by 7368697661** [comment]
Darn it, I thought I just fixed that! As far as I know, it's an issue with positioning of the check slider. 

e:
Oh gods, I fixed it recently, but I have no idea where the code is right now 🙈I'm going to have to take another look and try to remember what I did, but I want to say it was related to switching the after to position: fixed; maybe?

I'll take a look after work today :)

**Comment by 7368697661** [comment]
Should be fixed!

**Comment by imrehg** [comment]
Super stuff, cheers! :D I'll wait for the release to try it out.
