### ISSUE TITLE
Bug: Canvas doesn't look like I expect it to from the README

### ISSUE THREAD

**Issue by Akeboshiwind** [7368697661/Origami#16]
The README makes me expect that the canvas will look like this:
<img width="500" src="https://user-images.githubusercontent.com/87339163/208278021-a3489617-0511-4de5-bb3f-ed0dda125bf4.png">

But instead I've found it looks like this:
<img width="500" alt="Screen Shot 2023-02-12 at 12 04 08" src="https://user-images.githubusercontent.com/8889986/218309953-301712b0-5494-442e-aaad-24811ba754a1.png">

I actually don't mind too much but it doesn't seem this is intended from the README

**Comment by Akeboshiwind** [comment]
Hmm, groups also have the same effect.

Also this makes it so that it's hard to click on the handle to draw an arrow from a note that has an existing arrow on the same note FYI

**Comment by 7368697661** [comment]
there should be a much more stable version live now, sorry about that!
