### ISSUE TITLE
Feature Request: original color scheme

### ISSUE THREAD

**Issue by maudlinmandrake** [7368697661/Origami#18]
I really miss the original light blue & pink theme, and would love to see it available as an option in Style Settings

**Comment by 7368697661** [comment]
oh no im really sorry! i'll try to get it back in the next update💖

**Comment by 7368697661** [comment]
there should be a new shark time, i realize it isn't a 1:1 but let me know how this looks; i can change it around really easily now! :)

**Comment by maudlinmandrake** [comment]
> there should be a new shark time, i realize it isn't a 1:1 but let me know how this looks; i can change it around really easily now! :)

Aaah, this makes me so happy! Thank you <3
