### ISSUE TITLE
Dark mode doesn't seem to work with the default, blue custom accent

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#20]
When switching between Dark / Light mode, the theme didn't really seemed to have pick things up, except for the colours of the dropdowns, switches, etc.. But using Style Settings in addition, it seems th default "blue" custom accent is the one that doesn't switch to Dark properly, while the other custom accent appear to work fine.

Light mode:

<img width="1119" alt="Screenshot 2023-02-23 at 13 47 37" src="https://user-images.githubusercontent.com/38863/220829855-7723de62-dbf1-4722-b3d9-917d2a47c8fd.png">

Switched to Dark mode with all default Style Settings settings:

<img width="1129" alt="Screenshot 2023-02-23 at 13 46 07" src="https://user-images.githubusercontent.com/38863/220829758-d5ebd77a-145d-43ad-afb1-661ff3753496.png">

Experimentally switching to another custom accent in Dark mode, seem to switch everything.

<img width="1130" alt="Screenshot 2023-02-23 at 13 46 20" src="https://user-images.githubusercontent.com/38863/220829764-c8567c55-cd74-4ad6-b04b-85a00d759df4.png">

If I go back to "blue", it's like the 2nd screenshot again.

Using Origami 1.0.0.9

**Comment by 7368697661** [comment]
thanks for letting me know, i've been fiddling with blue (i think i found the issue there) and will have an update to test soon :)
