### ISSUE TITLE
Readability issues with unchecked checkboxes in light mode

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#21]
When using this theme and light mode setting (and otherwise everything else default too), unhecked checkboxes seem to blend in completely

The second line has an unchecked checkbox:

<img width="395" alt="Screenshot 2023-02-23 at 13 54 59" src="https://user-images.githubusercontent.com/38863/220830743-ab08723e-ff5a-456d-859e-5c607f7a8998.png">

Here's checking the checkbox for reference:

<img width="414" alt="Screenshot 2023-02-23 at 13 55 10" src="https://user-images.githubusercontent.com/38863/220830748-150a1d65-1f62-434d-8497-38d471b7f217.png">

Using Origami 1.0.0.9

**Comment by 7368697661** [comment]
i just pushed a potential fix, can you let me know if it looked better?

**Comment by imrehg** [comment]
@7368697661 thanks for the heads up, I've checked it out and it seems to be very nicely readable in all the settings combinations I've tried. I think this can be considered closed from my side. Cheers for this! 👏
