### ISSUE TITLE
No text selection color on most themes

### ISSUE THREAD

**Issue by frankreporting** [7368697661/Origami#22]
In "low contrast," "fff/000," and other theme modes, when you highlight text, there's no background color, so you can't really see what you're highlighting.

Text selection background only seems to be visible with "accent tinted," "architect," "soft," and "soft low contrast."

I'm on version Origami version 1.0.0.9 and Obsidian version 1.1.15.

**Comment by frankreporting** [comment]
Update: It appears to be because the text highlight is using the --background-secondary color variable. Maybe text highlight color should be set independently?

**Comment by 7368697661** [comment]
ahhh i see, that was a massive oversight. since it uses background secondary, the way i have those low contrast themes set up means that it would most likely match the background! thanks for pointing this out, and there should be a fix now :)
