### ISSUE TITLE
Hyperlink not so obvious

### ISSUE THREAD

**Issue by deskside** [7368697661/Origami#23]
Image 1 and Image 2 have the same text.

But I can barely tell the difference between hyperlink and plain text until I click on it.

Is this a feature, a bug or something I haven't set properly?

( And thanks a lot for this elegant theme !!! I love it ! )

<img width="747" alt="image" src="https://user-images.githubusercontent.com/68626438/221056386-a36ccd08-1c26-4ed6-9a84-b499b68c26fb.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/68626438/221056410-1d5087b8-9acd-424c-a318-52fa541af54d.png">

**Comment by 7368697661** [comment]
ohhhh i think external links just had a bold effect, which might not work on non-variable fonts! i like to keep links minimal (and thank you so much for the kind words!!) so for now i added a small link icon. let me know how it looks!
