### ISSUE TITLE
Alternate Fonts for Headers

### ISSUE THREAD

**Issue by JustinThomason** [7368697661/Origami#24]
I really dig the aesthetic of the theme. I just wish I could set the Header font (specifically H1) to the Fraunces font used for the inline title. I do not use the inline title feature for various reasons, so my H1 is by default the page title. Adding the option to change the Header font in Style Settings would be amazing!

**Comment by 7368697661** [comment]
there should now be an option for h1 in style settings, i'll look into more options in the future and make sure to wrap these in :)

**Comment by JustinThomason** [comment]
Woot! Thanks for adding the H1 style options.
