### ISSUE TITLE
Heading sizes not kept

### ISSUE THREAD

**Issue by DutchPete** [7368697661/Origami#25]
Style Settings > Typography > Heading Settings > Header Size Arrays

The default setting is *Opinionated*. However, in the drop-down one can choose the “empty” choice, which lets heading sizes as per my snippet prevail. Great!

But when I reload Obsidian, the *Opinionated* sizes are imposed again, even though in the drop-down the empty choice is still selected.

**Comment by 7368697661** [comment]
oh that is so weird, i'll take a look at that; thanks for bringing it to my attention!

**Comment by DutchPete** [comment]
Yep, that is a nuisance indeed.

**Comment by 7368697661** [comment]
Can you let me know if the latest push has the same issue?

**Comment by DutchPete** [comment]
The issue is resolved. Note: I don't see the *Header size arrays* option anymore.
