### ISSUE TITLE
Change background color dark mode does not work

### ISSUE THREAD

**Issue by DutchPete** [7368697661/Origami#27]
Style Settings > Color Palettes > Primary
Default is #000. One can change the color number, but nothing changes in the main panel showing the note.

**Comment by 7368697661** [comment]
hi! are you referring to these options?
![image](https://user-images.githubusercontent.com/87339163/223571708-56583d50-ae89-4eeb-af79-952010f5fa7f.png)

super sorry it was so confusing, but those settings only affect these color schemes:
![image](https://user-images.githubusercontent.com/87339163/223571906-5ed69471-5230-4a6a-bc71-0b1bf7b731e2.png)
(there should be options to set different colors for each mode)

**Comment by DutchPete** [comment]
Yes, that is what I meant.

For Light I like the *soft* theme. But for dark I want a different primary color.

![image](https://user-images.githubusercontent.com/10794265/223657897-ccbcc6c0-47a0-4ef6-81f8-85e699a7c9fb.png)


I am not sure how to do this.

**Comment by DutchPete** [comment]
I figured it out. My apologies for the confusion.
