### ISSUE TITLE
Multiple "themes" drop-down in Style Settings 

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#30]
I've been checking Origami adjusting through the Style Settings plugin, and multiple "Themes" dropdown seem to be showing up. I believe only the one on the top changes anything, the bottom one doesn't seem to have any effect. This sort of thing (duplicate entries for anything) doesn't seem to happen for other plugins, so the hunch is that it's more in Origami rather than Style Settings.

Screenshot of the part withing Color Palettes:

<img width="767" alt="Screenshot 2023-03-06 at 13 58 16" src="https://user-images.githubusercontent.com/38863/223030677-095a0e12-69d1-4881-aa56-424b5e6c960e.png">

**Comment by trevware** [comment]
I believe the top one affects Light Themes, while the bottom is Dark. I believe the labelling is still incorrect though.

**Comment by 7368697661** [comment]
thanks for catching this! it is indeed simply an issue from switching back to separate dark and light modes; should have a fix coming in the next update :) the top field should switch light color themes, and the bottom field should offer dark mode themes. can you confirm if the dark mode switch does nothing while in dark mode?

**Comment by 7368697661** [comment]
forgot to close this, but should be fixed. tysm for the heads up!
