### ISSUE TITLE
Blueprint style setting leaves dropdowns unreadable unless focused

### ISSUE THREAD

**Issue by imrehg** [7368697661/Origami#32]
In Dark mode, using the Style settings and `Blueprint` leaves dropdowns unreadable (background + font colour combo):

<img width="799" alt="Screenshot 2023-03-08 at 18 09 26" src="https://user-images.githubusercontent.com/38863/223685606-8bf76de6-2ee4-4186-be63-fca047a8cb4a.png">

If I click in the dropdown to gain focus, then it becomes readable:

<img width="797" alt="Screenshot 2023-03-08 at 18 09 31" src="https://user-images.githubusercontent.com/38863/223685622-15bc27d8-12fd-44b6-9e10-e235496baa01.png">

Using Origami 1.9.0.1

**Comment by 7368697661** [comment]
1.9.0.2 should fix this! let me know if its still happening :)
