### ISSUE TITLE
Large space after URL links.

### ISSUE THREAD

**Issue by JohnKnoepfle** [7368697661/Origami#34]
I just started using Origami and I really like it!  It is beautiful in both light and dark mode.

I've noticed there's a large space or padding after URL links.   You can see it in the screenshot below.   I'm using dark mode and I'm running it on a Macbook Pro with an M1 chip.   Not sure if that matters or not.

<img width="747" alt="Screen Shot 2023-03-08 at 9 27 25 AM" src="https://user-images.githubusercontent.com/9356470/223755257-94925d8c-a0c2-4556-b724-e39328afb000.png">

**Comment by JohnKnoepfle** [comment]
I just realized when I double checked it in light mode that the space is actually the "link" symbol/icon.   It's just not visible in dark mode.

**Comment by 7368697661** [comment]
let me know if that looks any better, i replaced it with a dot for reading now and minimal styling in live preview
