### ISSUE TITLE
Mobile: Can't dismiss popup windows like quick switcher

### ISSUE THREAD

**Issue by frankreporting** [7368697661/Origami#35]
I have iOS14, and I notice that when I use Origami on mobile, and when I pull up the quick switcher, it's so big that there's no space on the screen to click _outside_ the popup. That effectively leaves no way to dismiss the popup, so you're stuck force closing the app or else switching to another note and then having to switch back.

Expected behavior: If the popup were slightly smaller than the editor background, then you could tap above it or outside it to get it to disappear, in the case that you decided not to switch to another note.

Also, I just want to say, I imagine building a theme is hard. I really appreciate the work you've done on Origami. It's brilliant, deceptively simple, and beautiful!

**Comment by 7368697661** [comment]
I'll take a look, thank you so much for your patience (and for the kind words, that truly means quite a bit!). I'll see what I can do :)

**Comment by 7368697661** [comment]
ok let me know if that works?

**Comment by frankreporting** [comment]
> ok let me know if that works?

That worked thanks!
