### ISSUE TITLE
Collapsing right sidebar can't be expanded again

### ISSUE THREAD

**Issue by gork3n** [7368697661/Origami#6]
When you collapse the right sidebar, it seems to collapse under the invisible 'exit' button. I am unable to expand the sidebar again unless I change themes. 

The expand button is not clickable, only the 'exit' button reveals on mouseover.
![69bd1b59d8daeb92cbb136bef66320e3](https://user-images.githubusercontent.com/1086155/206822078-9986e9fe-de28-40dd-a27b-774f39fc31ae.gif)

**Comment by 7368697661** [comment]
This should be fixed in the new version! :)
