### ISSUE TITLE
[Bug?] External links in Markdown not visible

### ISSUE THREAD

**Issue by RachelVeer** [7368697661/Origami#7]
Whenever I have external Markdown links, e.g. `[markdown-link](https://link.com)`, it does not render in Reading view; these links are visible however when editing in both Live Preview and Source mode. 

OS: Windows 11, Obsidian desktop app version: 1.0.3.

If you need anymore information, let me know. And if you can't replicate this issue, and it's just mysteriously on my end - sorry! Love the theme, and this is my only issue by far. (Internal links are perfectly fine.)

**Comment by 7368697661** [comment]
hi friend! that was entirely my fault haha. i was trying to turn off that arrow at the end of external links and accidentally turned off external links entirely 😅 it should be fixed in the new version on the Obsidian theme store!
