### ISSUE TITLE
Contrast is too low for bold text, italic text, and links

### ISSUE THREAD

**Issue by joelatschool** [7368697661/Origami#8]
I love the theme but I find it hard to use as a daily driver bc the contrast with the background of bold text, italic text, and links is very low, which makes link and bold-text heavy MOCs especially hard to read:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/94202132/212147043-40536728-d553-4697-a8f7-92666ed8ebcf.png">
(ignore the blue links and ※'s, those are coming from another extension)

Please add a setting to increase the contrast for these.

**Comment by 7368697661** [comment]
Ow wow yeah that's bad haha. I was actually going to do some work on Origami over the weekend, stay tuned for changes :) I need to redo some of the contrast across the board and open the theme up to style settings. Thanks for the heads up!

**Comment by 7368697661** [comment]
There should be a new version up, let me know if it looks any better to you :)

**Comment by joelatschool** [comment]
Thanks! The new version is definitely more readable, but there doesn't seem to be any styling happening for bold or italic text:
<img width="133" alt="image" src="https://user-images.githubusercontent.com/94202132/212552155-b4d9852b-f437-4c6c-abbb-0e2e6b74007b.png">
I'll make a new issue for that.
