### ISSUE TITLE
No styling happening for bold or italic body text

### ISSUE THREAD

**Issue by joelatschool** [7368697661/Origami#9]
In the current version of the theme, there's no styling happening for either bold or italic body text:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/94202132/212552355-97bb1464-864b-4cac-ab8b-e199c0c4c4ce.png">
<img width="133" alt="image" src="https://user-images.githubusercontent.com/94202132/212552308-8ecd25fb-a722-4464-94ca-792b33c31951.png">

**Comment by 7368697661** [comment]
Ok, should be fixed! Thanks for letting me know :)
